kind: pipeline
name: Build and Deploy
type: docker

steps:
  - name: Restore Cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./.next/cache
  - name: Install Dependancies
    pull: if-not-exists
    image: node:lts-bullseye-slim
    commands:
      - yarn install --frozen-lockfile
  - name: Build
    pull: if-not-exists
    image: node:lts-bullseye-slim
    commands:
      - yarn build
  - name: Publish
    image: plugins/docker
    when:
      branch:
        - main
    pull: if-not-exists
    settings:
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_password
      repo: ghcr.io/sebasptsch/tduwebsite
      registry: ghcr.io
      auto_tag: true
  - name: Rebuild Cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./.next/cache

volumes:
  - name: cache
    host:
      path: /tmp/cache
